### ISSUE TITLE
注解需要适配下kotlin

### ISSUE THREAD

**Issue by tx123456** [CodeXiaoMai/EnvironmentSwitcher#10]
当使用kotlin-kapt 的时候，会提示错误: 找不到符号
符号:   类 EnvironmentSwitcher
位置: 程序包 com.xiaomai.environmentswitcher

**Comment by CodeXiaoMai** [comment]
> 注意：如果你的项目中使用了 Kotlin，请使用 Java 语言编写 EnvironmentConfig，就像在 GreenDao 中必须使用 Java 语言编写 Entity 类一样。

所以建议先使用  Java 编写 EnvironmentConfig

**Comment by tx123456** [comment]
这边EnvironmentConfig这个类是用java编写的，但是使用kapt这个插件之后编译项目提示无法找到com.xiaomai.environmentswitcher

**Comment by CodeXiaoMai** [comment]
方便把你的以下信息发给我吗？
- 顶层 build.gradle 中的配置
- 主工程目录下的 build.gradle 的脱敏信息
- Android Studio 版本
- gradle-wrapper.properties中的 gradle 版本

**Comment by tx123456** [comment]
一开始没注意文档里面还有kotlin的依赖，我这边吧依赖替换成kotlin的就好了
