### ISSUE TITLE
release 包的话 无法切换地址

### ISSUE THREAD

**Issue by wangtao2855** [CodeXiaoMai/EnvironmentSwitcher#17]
![image](https://user-images.githubusercontent.com/34060120/70032954-7ef88180-15e9-11ea-91f7-8bc2e1102f83.png)

**Comment by CodeXiaoMai** [comment]
关于release包为什么不能切换环境，在readme里面有介绍，是为了防止测试地址随安装包发布后会泄漏。

**Comment by wangtao2855** [comment]
> readme

有没有什么办法放开 因为会有这么一个需求 就是我给测试打包的时候全部都是release包. 如果打debug包的话 我怕跟release包有不一样的地方

**Comment by CodeXiaoMai** [comment]
你可以尝试把 

```
kaptDebug "com.xiaomai.environmentswitcher:environmentswitcher-compiler:$environment_switcher_compiler_version"
kaptRelease "com.xiaomai.environmentswitcher:environmentswitcher-compiler-release:$environment_switcher_compiler_version"
```

里面的 kaptDebug 和 kaptRelease 都使用 debug 模式的 compiler，然后在调用 `EnvironmentSwitcher.getXXEnvironment()` 的 isDebug参数传入 true。

https://www.jianshu.com/p/190710a846b9 这是EnvironSwitcher 的原理，搞明白原理问题就能迎刃而解了。祝你成功！！！

**Comment by wangtao2855** [comment]
> 你可以尝试把
> 
> ```
> kaptDebug "com.xiaomai.environmentswitcher:environmentswitcher-compiler:$environment_switcher_compiler_version"
> kaptRelease "com.xiaomai.environmentswitcher:environmentswitcher-compiler-release:$environment_switcher_compiler_version"
> ```
> 
> 里面的 kaptDebug 和 kaptRelease 都使用 debug 模式的 compiler，然后在调用 `EnvironmentSwitcher.getXXEnvironment()` 的 isDebug参数传入 true。
> 
> https://www.jianshu.com/p/190710a846b9 这是EnvironSwitcher 的原理，搞明白原理问题就能迎刃而解了。祝你成功！！！

谢谢老板 爱你 😍
