### ISSUE TITLE
关于 EnvironmentSwitcher 无法生成问题

### ISSUE THREAD

**Issue by DouglasQA** [CodeXiaoMai/EnvironmentSwitcher#18]
可以尝试下使用 com.android.tools.build:gradle:3.5.3、gradle-5.4.1-all.zip

会发现并未生成 EnvironmentSwitcher （无论是依赖库，或者拉该库代码直接运行，都没有生成）debugAnnotationProcessor 修改为 annotationProcessor 也一样不会调用 AbstractProcessor 继承类执行生成的代码

**Comment by CodeXiaoMai** [comment]
我试了一下，没问题呢。你是按Readme里面的步骤依次操作的吗

**Comment by nEdAy** [comment]
我也是..试了几个姿势 没有生成EnvironmentSwitcher

gradle-6.5-all.zip
classpath 'com.android.tools.build:gradle:4.1.2'

**Comment by nEdAy** [comment]
抱歉 可以了 是我操作问题 isRelease多个为true了

**Comment by CodeXiaoMai** [comment]
@nEdAy 哈哈，成功了就好，🎉
